name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  permission_handler: ^11.3.1
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  lottie: ^3.1.3
  



dev_dependencies:
  freezed: ^2.4.4
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/catloading.json  # Corrected asset path
